name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:latest
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Redis connection
      run: |
        python -c "import redis; r = redis.Redis(); r.ping(); print('Redis OK')"
    
    - name: Test script syntax
      run: |
        python -m py_compile get-kepler-dr25.py
        python -m py_compile filter-get-kepler-dr25.py
        python -m py_compile util/*.py
        echo "All scripts compile successfully"
    
    - name: Check script help
      run: |
        python get-kepler-dr25.py --help
        python filter-get-kepler-dr25.py --help
    
    - name: Run basic download test (if needed)
      run: |
        echo "Skipping download test to avoid MAST rate limits"