name: Publish to TestPyPI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test-publish:
    name: Build and publish to TestPyPI
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/kepler-downloader-dr25/
    
    permissions:
      id-token: write  # Required for trusted publishing
      contents: read
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
        pip install -r requirements.txt
    
    - name: Build package
      run: python -m build
    
    - name: Check distribution
      run: |
        ls -la dist/
        python -m twine check dist/*
    
    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        verbose: true
        print-hash: true
        skip-existing: true